server {
    listen 443 ssl;
    server_name cas.chirocity.gov.et;
    ssl_certificate /etc/letsencrypt/live/cas.chirocity.gov.et/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cas.chirocity.gov.et/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 50m;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location / {
        set $cas_upstream http://cas-web:3000;
        proxy_pass $cas_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name cas-api.chirocity.gov.et;
    ssl_certificate /etc/letsencrypt/live/cas.chirocity.gov.et/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cas.chirocity.gov.et/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 50m;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location /media/ {
        set $cas_media http://cas-files:80;
        proxy_pass $cas_media;
        proxy_set_header Host $host;
    }
    location / {
        set $cas_upstream http://cas-api:8000;
        proxy_pass $cas_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
